name: Build and publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD
    - name: Use current time
      env:
        YEAR: "${{ steps.current-time.outputs.year }}"
        MONTH: "${{ steps.current-time.outputs.month }}"
        DAY: "${{ steps.current-time.outputs.day }}"
        VERSION: ${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }}.${{ github.run_number }}
      run: echo "nuget_version=$VERSION" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        nuget-api-key: ${{ secrets.PACKAGES_TOKEN }}
        nuget-version: '5.x'
    - name: Build
      run: dotnet build -p:Version=${{ env.nuget_version }} --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: nuget pack *.csproj -Properties Configuration=Release -Version ${{ env.nuget_version }}
    - name: Publish
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGES_TOKEN }} --source "https://nuget.pkg.github.com/makehyphen/index.json"  